# Generated by Django 4.2.7 on 2023-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0001_initial'),
        ('article_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comment_app.comment'),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default='Random Text'),
            preserve_default=False,
        ),
    ]
