# Generated by Django 4.2.7 on 2023-11-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_article_comments_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='articles'),
            preserve_default=False,
        ),
    ]
